export const viewSetActionNameGenerator_setListLoading = (name) => `viewset/${name}/setListLoading`;
export const viewSetActionNameGenerator_setResults = (name) => `viewset/${name}/setResults`;
export const viewSetActionNameGenerator_setResultItem = (name) => `viewset/${name}/setResultItem`;
export const viewSetActionNameGenerator_setOrder = (name) => `viewset/${name}/setOrder`;
export const viewSetActionNameGenerator_setFilters = (name) => `viewset/${name}/setFilters`;
export const viewSetActionNameGenerator_editInline = (name) => `viewset/${name}/editInline`;
export const viewSetActionNameGenerator_cancelInlineEdit = (name) => `viewset/${name}/cancelInlineEdit`;
export const viewSetActionNameGenerator_updateInlineField = (name) => `viewset/${name}/updateInlineField`;
export const viewSetActionNameGenerator_clearInlineForm = (name) => `viewset/${name}/clearInlineForm`;
